# Generated by Django 3.1.4 on 2021-01-17 06:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('content', tinymce.models.HTMLField()),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
