# Generated by Django 3.1.4 on 2021-01-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(1, 'Arduino'), (2, 'Robotics'), (3, 'Articles')]),
        ),
    ]
